app_api:
    resource: "@AppBundle/Controller/Api"
    type: annotation

app_web:
    resource: "@AppBundle/Controller/Web"
    type: annotation

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"
