parameters:
  app.api.route.prefix: 'app_api'

services:
  json_exception_listener:
    class: 'AppBundle\EventListener\JsonExceptionListener'
    arguments:
      apiRoutePrefix: '%app.api.route.prefix%'
    tags:
      - { name: kernel.event_listener, event: kernel.exception, method: onKernelException, priority: 200 }