imports:
    - { resource: 'json_api.request_parsers.yml' }
    - { resource: 'custom_validators.yml' }

parameters:
  app.api.route.prefix: 'app_api'

  security.pin.alphabet: '0123456789ABCDEFGJKHILMNOPQRSTUVWXYZ'
  security.pin.length: 4
  security.pin.duration: 84000 #seconds

  security.token.alphabet: '0123456789ABCDEFGJKHILMNOPQRSTUVWXYZ.-_%&$~*'
  security.token.length: 16
  security.token.duration: 84000 #seconds

  security.event.user_registered_event: 'user.registered'

services:
  security.confirmation_pin_builder:
      class: AppBundle\Service\Security\ConfirmationPinBuilder
      arguments:
          alphabet: '%security.pin.alphabet%'
          length: '%security.pin.length%'

  security.confirmation_token_builder:
      class: AppBundle\Service\Security\ConfirmationTokenBuilder
      arguments:
          alphabet: '%security.token.alphabet%'
          length: '%security.token.length%'

  security.user_builder:
      class: AppBundle\Service\Security\UserBuilder
      arguments:
          pe: "@security.password_encoder"
          cpb: "@security.confirmation_pin_builder"
          ctb: "@security.confirmation_token_builder"

  security.orm_user_persister:
      class: AppBundle\Service\Security\ORMUserPersister
      arguments:
          em: "@doctrine.orm.entity_manager"

  json_api.event_listener.json_exception_listener:
      class: 'AppBundle\Service\JsonApi\EventListener\JsonExceptionListener'
      arguments:
          apiRoutePrefix: '%app.api.route.prefix%'
      tags:
          - { name: kernel.event_listener, event: kernel.exception, method: onKernelException, priority: 200 }

  json_api.validator.json_request_validator:
      class: AppBundle\Service\JsonApi\Validator\JsonRequestValidator

  json_api.deserializer.json_api_request_deserializer:
      class: AppBundle\Service\JsonApi\Deserializer\JsonApiRequestDeserializer

  json_api.serialier.json_api_serializer:
      class: AppBundle\Service\JsonApi\Serializer\JsonApiSerializer
      arguments:
          em: '@doctrine.orm.entity_manager'

  json_api.response.json_api_response_builder:
      class: AppBundle\Service\JsonApi\Response\JsonApiResponseBuilder
      arguments:
          serializer: '@json_api.serialier.json_api_serializer'
