parameters:
  app.api.route.prefix: 'app_api'

services:
  app.fake_user_provider:
    class: 'AppBundle\Service\FakeUserProvider'
    arguments:
      em: '@doctrine.orm.default_entity_manager'

  json_exception_listener:
    class: 'AppBundle\EventListener\JsonExceptionListener'
    arguments:
      apiRoutePrefix: '%app.api.route.prefix%'
    tags:
      - { name: kernel.event_listener, event: kernel.exception, method: onKernelException, priority: 200 }